### ISSUE TITLE
EZSP 6.10.0.0 GA

### ISSUE THREAD

**Issue by MattWestb** [xsp1989/zigbeeFirmware#18]
Silabs have released [Zigbee EmberZNet SDK 6.10.0.0 GA](https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.10.0.0.pdf). 

But i have not finding any interesting fixes in the Zigbee stack but in the Gecko Platform 3.2.0.0 GA (Simplicity Studio 5) i have finding some interesting fixes that perhaps can helping:

- 703231 Fixed an issue in Power Manager on Series 2 devices where we could get stuck waiting for HFXO to be ready when a hardware request on HFXO was removed in the middle of the restore process in Power Manager.
- 675253 Fixed an issue in Power Manager where, if the HFXO startup failed while actively waiting for it to be ready in a critical section, we could wait indefinitely
- 697483 Fixed bug affecting CTUNE for HFXO on Series 2 devices.

I think the 2 first is not relevant but the last looks "fitting" in the picture.

I think it can being worth one shut testing is its helping users that still having problems with there sleeping end devices.

Wot i can see in ZHA was the EZSP 6.7.8.0 helping many users with this problem and the CTune fix in 6.7.9.0 was also doing but its still some users that having fast battery draining (48 hours = OTA updating all the time for 2 days).

I dont have the device but have running ZHA with one tuya MG21 module that have the same chip and its working great with cooked EZSP 6.7.9 0 and 6.9.2.0 on one WeMos D1 Mini running tasmota or ESPHome for weeks with 7 different IKEA remotes.

Then Silabs have updating the compilers i think it can being good doing extra testing before relenting new firmware then its very likely getting new bugs implanted that can needing time for being pinpointed and fixes from Silabs side.

And one great thanks for supporting the community and i think in the end its one win win situation for both !!!

Mvh  Mattias

**Comment by Hedda** [comment]
+1 requesting EmberZNet 6.10.0.0 (Silabs Zigbee NCP EmberZNet 6.10.0) firmware for ITead Zigbee 3.0 USB Dongle

**Comment by Hedda** [comment]
Again, I also like to suggest looking at increasing default configuration parameters in a "pro" firmware as suggested in https://github.com/xsp1989/zigbeeFirmware/issues/6 and https://github.com/xsp1989/zigbeeFirmware/pull/13

Configuration Parameter | Value
-- | --
Part | EFR32MG21A020F768IM32
Version | EZSP 6.10.0.0
CTUNE value | 128
Address Table Size | 32
Child Table Size | 64
Source Routes | 200
TX | PB01
RX | PB00
CTS | ?
RTS | ?
BTL | PA00 (Low = BTL boot)
LED | PC00 

As I understand these are the "pro" configuration that tube0013 use in his EFR32MG21 Zigbee Coordinator Gateway devices (or?):

 # Specific Configuration for the Tube EFR32 Gateways
Because the EFR32 gateways uses some firrmware settings different than the bellows defaults it is recommended set them in the configuration.yaml so bellows will utilize them.


## For EFR32 Series 2 Gateways with Firmware based on the 6.9.2 SDK please use the following config
**Add these lines to your configuration.yaml file:**

```
zha:
  zigpy_config:
    source_routing: true
    ezsp_config:
      CONFIG_APS_UNICAST_MESSAGE_COUNT: 64
      CONFIG_MAX_END_DEVICE_CHILDREN: 32
      CONFIG_SOURCE_ROUTE_TABLE_SIZE: 200
      CONFIG_ROUTE_TABLE_SIZE: 16
      CONFIG_ADDRESS_TABLE_SIZE: 32
      CONFIG_PACKET_BUFFER_COUNT: 250
      CONFIG_BINDING_TABLE_SIZE: 32
      CONFIG_NEIGHBOR_TABLE_SIZE: 26
```
