### ISSUE TITLE
[SUGGESTION] Increase default configuration parameters in firmware ITead Zigbee 3.0 USB Dongle

### ISSUE THREAD

**Issue by Hedda** [xsp1989/zigbeeFirmware#6]
Suggest increasing some of the default configuration parameters in firmware for ITead Zigbee 3.0 USB Dongle and SM-011.

Configuration Parameter | Value
----------------------- | ------
Address Table Size | 32
Child Table Size | 32
Source Routes | 200

That in firmware would make ITead Zigbee 3.0 USB Dongle and SM-011 be classified as a "pro" device as per https://github.com/zigpy/bellows/pull/397

I do not think that changing those should cause any regressions as max can be set in the application or inherit from the NCP.

EFR32MG21 MCU used in ITead Zigbee 3.0 USB Dongle and SM-011 is certainly powerful/sized enough to support it.

Note that while this is supported by zigpy/bellows https://github.com/zigpy/bellows/pull/397 but cannot yet be utilized in downstream HA's ZHA.

PS: This has been tested by tube0013 with his EFR32 based gateway/bridge

See example of used in real life 

https://github.com/tube0013/tube_gateways

https://github.com/tube0013/tube_gateways/blob/main/tube_zb_gw_efr32/README.md

 # Specific Configuration for the Tube EFR32 Gateways
Because the EFR32 gateways uses some firrmware settings different than the bellows defaults it is recommended set them in the configuration.yaml so bellows will utilize them.

## For EFR32 Series 2 Gateways with Firmware based on the 6.9.2 SDK or later please use the following config
**Add these lines to your configuration.yaml file:**

```
zha:
  zigpy_config:
    source_routing: true
    ezsp_config:
      CONFIG_APS_UNICAST_MESSAGE_COUNT: 64
      CONFIG_MAX_END_DEVICE_CHILDREN: 32
      CONFIG_SOURCE_ROUTE_TABLE_SIZE: 200
      CONFIG_ROUTE_TABLE_SIZE: 16
      CONFIG_ADDRESS_TABLE_SIZE: 32
      CONFIG_PACKET_BUFFER_COUNT: 250
      CONFIG_BINDING_TABLE_SIZE: 32
      CONFIG_NEIGHBOR_TABLE_SIZE: 26
```

https://github.com/tube0013/tube_gateways/blob/main/tube_zb_gw_efr32/README.md

> > you can do `bellows -d /dev/ttyUSBx config --all` it would print the ~current~ default, out of the box settings
> 
> this is with children set to 32 in fw.
> 
> ```
> NOTE: Configuration changes do not persist across resets
> CONFIG_PACKET_BUFFER_COUNT=254
> CONFIG_NEIGHBOR_TABLE_SIZE=26
> CONFIG_APS_UNICAST_MESSAGE_COUNT=30
> CONFIG_BINDING_TABLE_SIZE=32
> CONFIG_ADDRESS_TABLE_SIZE=32
> CONFIG_MULTICAST_TABLE_SIZE=8
> CONFIG_ROUTE_TABLE_SIZE=16
> CONFIG_DISCOVERY_TABLE_SIZE=8
> CONFIG_STACK_PROFILE=0
> CONFIG_SECURITY_LEVEL=5
> CONFIG_MAX_HOPS=30
> CONFIG_MAX_END_DEVICE_CHILDREN=32
> CONFIG_INDIRECT_TRANSMISSION_TIMEOUT=3000
> CONFIG_END_DEVICE_POLL_TIMEOUT=8
> CONFIG_TX_POWER_MODE=0
> CONFIG_DISABLE_RELAY=0
> CONFIG_TRUST_CENTER_ADDRESS_CACHE_SIZE=0
> CONFIG_SOURCE_ROUTE_TABLE_SIZE=200
> CONFIG_FRAGMENT_WINDOW_SIZE=1
> CONFIG_FRAGMENT_DELAY_MS=0
> CONFIG_KEY_TABLE_SIZE=12
> CONFIG_APS_ACK_TIMEOUT=1600
> CONFIG_ACTIVE_SCAN_DURATION=3
> CONFIG_END_DEVICE_BIND_TIMEOUT=60
> CONFIG_PAN_ID_CONFLICT_REPORT_THRESHOLD=2
> CONFIG_REQUEST_KEY_TIMEOUT=0
> CONFIG_CERTIFICATE_TABLE_SIZE=0
> CONFIG_APPLICATION_ZDO_FLAGS=0
> CONFIG_BROADCAST_TABLE_SIZE=15
> CONFIG_MAC_FILTER_TABLE_SIZE=0
> CONFIG_SUPPORTED_NETWORKS=1
> CONFIG_SEND_MULTICASTS_TO_SLEEPY_ADDRESS=0
> CONFIG_ZLL_GROUP_ADDRESSES=1
> CONFIG_ZLL_RSSI_THRESHOLD=128
> CONFIG_MTORR_FLOW_CONTROL=1
> CONFIG_RETRY_QUEUE_SIZE=16
> CONFIG_NEW_BROADCAST_ENTRY_THRESHOLD=9
> CONFIG_TRANSIENT_KEY_TIMEOUT_S=300
> CONFIG_BROADCAST_MIN_ACKS_NEEDED=255
> CONFIG_TC_REJOINS_USING_WELL_KNOWN_KEY_TIMEOUT_S=300
> CONFIG_CTUNE_VALUE=282
> CONFIG_ASSUME_TC_CONCENTRATOR_TYPE=1```
> ```

**Comment by Hedda** [comment]
@xsp1989  Again I am not a firmware developer but maybe also increase "Address Table Size" to 32 and "Source Routes" to 200?

Configuration Parameter | Value
----------------------- | ------
Address Table Size | 32
Child Table Size | 64
Source Routes | 200
CTUNE value | 128

At least that is what I understand that tube0013 has configurated his EFR32MG21 based gateway/bridge to use?

https://github.com/tube0013/tube_gateways/blob/main/tube_zb_gw_efr32/README.md

**_Because the EFR32 gateways uses some higher firmware settings it is recommended set them in the configuration.yaml so bellows will utilize them._**

**_Add these lines to your configuration.yaml file:_**

```
zha:
  zigpy_config:
    source_routing: true
    ezsp_config:
      CONFIG_APS_UNICAST_MESSAGE_COUNT: 30
      CONFIG_MAX_END_DEVICE_CHILDREN: 64
      CONFIG_SOURCE_ROUTE_TABLE_SIZE: 200
      CONFIG_ROUTE_TABLE_SIZE: 16
      CONFIG_ADDRESS_TABLE_SIZE: 32
      CONFIG_PACKET_BUFFER_COUNT: 254
      CONFIG_BINDING_TABLE_SIZE: 32
      CONFIG_NEIGHBOR_TABLE_SIZE: 26
```
